### ISSUE TITLE
When sticky header on: On loading the header's height 'might' be set with a wrong value in Safari

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#554] opened 2017-08-09 07:41 UTC
https://secure.helpscout.net/conversation/403100633/30291/?folderId=607709

It correctly appears after a window's resizing.
Cannot reproduce this on the demo.

**Comment by eri-trabiccolo** [comment] 2018-01-25 10:47
Probably related to this:
https://wordpress.org/support/topic/header-sometimes-loads-with-height-1px/

**Comment by robinckarlsson** [comment] 2018-02-05 09:18
HI! I'm the person who posted the issue above (.... header-sometimes-loads-with-height-1px/), and I really need a way to fix this. Close to half my visitors use Safari, so this is not acceptable. It does indeed appear correctly after resizing window.

**Comment by ghost** [comment] 2018-02-05 09:25
@robinckarlsson thank you for reporting the bug.
I cannot reproduce this problem with Safari on your website for the moment. But this will be investigated again before releasing the next release.

**Comment by robinckarlsson** [comment] 2018-02-05 09:27
@Nikeo Ok great, thanks.

**Comment by robinckarlsson** [comment] 2018-03-01 12:12
@Nikeo So I just updated everything and the issue persists. This needs to be fixed, as I previously mentioned more or less half my visitors use Safari and so potentially experiences this problem. I've recreated the issue on two completely different computers with different versions of Mac OS X and Safari, so you should be able to too. Just hit refresh a couple times and it should happen.

**Closed as completed** 2019-11-28 14:23 UTC
Labels: bug, question, cant-reproduce, Triage-2019
