### ISSUE TITLE
Header image issue on mobile ?

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#783] opened 2019-03-26 16:18 UTC
Can reproduce ?
https://wordpress.org/support/topic/header-image-not-displayed-any-longer/#post-11354507

**Comment by eri-trabiccolo** [comment] 2019-03-26 16:21
Nope, not able to reproduce on my smartphone either.

**Comment by ghost** [comment] 2019-03-26 16:54
ok thanks for the quick feedback

**Comment by ghost** [comment] 2019-03-26 16:55
ah thanks for requesting the troubleshooting process to the user. I should have done that !

**Comment by eri-trabiccolo** [comment] 2019-03-26 16:57
I did it only because I see that image is "also" lazyloaded, by a third party plugin, though I cannot reproduce any issue.

**Comment by eri-trabiccolo** [comment] 2019-03-27 09:15
I close this as the user confirms there's no issue.
https://wordpress.org/support/topic/header-image-not-displayed-any-longer/#post-11358981
> Hi,
> 
> you were right, of course 🙁 Mea culpa maxima! I didn’t deactivate all plugins, but only those that I considered to be responsible.
> 
> Finally, after deactivating EWWW Image Optimizer, everything worked. Therefore, I will get in touch with the developer and report the issue there. That means also that there is no issue with Autoptimize!
> 
> Sorry for that!
> 
> All the best and thanks for your support,
> Andreas

**Closed as completed by eri-trabiccolo** 2019-03-27 09:15 UTC
Labels: bug, invalid, question, cant-reproduce
