### ISSUE TITLE
version 3.4.9 - serious bug

### ISSUE THREAD

**Issue by mayazir** [AlxMedia/hueman#733] opened 2018-12-13 17:04 UTC
I used before during a few month version 3.3.25 and a few days ago updated to version 3.4.9.
Today I wanted to add mobile icon from "customization" and the button doesnt work.
Later I added a new widget to sidebar and then deleted it because I didnt like it, but the widget still was on the sidebar... I added another widgets but nothing more appear, not additional widgets, and not desappear an old one..
Then I added a div between footer and content, you can see it here: mexicanroutes.com (check the text above the footer. Then I tried to edit the text and.. nothing.. I saw edited text in footer.php and was sure I uploaded it, but no change on website itself.. I tried a few differents computers, the same bug..
The only solution to get updated file or widget was change the theme, I activated the 3.3.25 and then activated again 3.4.9 and it was the unique solution...
The same happened with another website - AncientMayanRuins.com

**Comment by mayazir** [comment] 2018-12-16 15:45
the same happens with 3.4.10
I add or edit widgets but dont see updates until I activate-desactivate the theme.

**Comment by ghost** [comment] 2018-12-16 15:47
Thanks for reporting the problem. I'll try to reproduce it on my end following your comments.

**Comment by ghost** [comment] 2019-01-10 09:09
I can't reproduce your issue.
Can you confirm that the problem occurs even when you disable all plugins ?

Can you also confirm that you are not using a child theme ? If you do use a child theme, then can you confirm that the problem occurs when you activate the main theme ?

Thanks !

**Comment by mayazir** [comment] 2019-01-10 14:58
Hi, it could be this plugin:
https://wordpress.org/plugins/wp-super-cache/
I use it at least 1 year, it is not a recent installed plugin, and I am sure it worked with old versions.
I desactivadet the plugin and activated it again, and now it seems to be OK, but I need to try more change to see the result and I cant now, the website is active and has traffic and I cant risk to damage it desactivating all plugins at the same time or making changes.
But I still cant upload a mobile logo in Customization.
For upload the mobile logo I had to switch to the 3.3.25 version and upload the mobile logo from there.

**Comment by mayazir** [comment] 2019-01-10 15:07
I dont use child theme but I add some lines to these files:
footer.php
functions.php
header.php
sidebar.php
sidebar-2.php
archive-tmpl.php
single-tmpl.php
I can email you all edited php if you want

**Comment by ghost** [comment] 2019-01-10 16:30
OK. cache plugin are often involved in this type of issues.

as a general rule, it's a good practice to disable any cache plugin when you customize your website.
After customizations are done, you can reactivate your cachec plugin, and clear its cache to make sure your live site reflects your latest changes.
I hope this can help, thanks.

**Comment by ghost** [comment] 2019-01-10 16:31
I'm closing the issue.

**Closed as completed by ghost** 2019-01-10 16:31 UTC
Labels: bug, question, Needs specifications
